This notebook walks through the analysis required to complete the tasks provided .

Q1: Use the provided CSV file named “GCL.csv” to apply the KNN classifier with k=3. Calculate the accuracy, sensitivity, and specificity. Note: Use the features from columns A to AA, and the labels from column AB?

Q2: Use the same file to apply the KNN classifier with k=5. Calculate the confusion matrix?

In [56]:
#fetch data 
import pandas as pd
df = pd.read_csv("GCL.csv", header=None)

In [57]:
#separate features and labels into X and y, respectively
X = df[df.columns[:-1]]
y = df[df.columns[-1]]

In [58]:
#split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [59]:
#implement KNN n=3
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

In [60]:
#evaluate accuracy, sensitivity, and specificity, acknolwedging that the data has 3 LABELS and not two
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix

overall_accuracy = accuracy_score(y_test, y_pred)
print("Overall Accuracy:", overall_accuracy)


#this confusion matrix gives us the data we need to calculate the asked for metrics (TP, TN, FP, FN for each class since this is a trinary classification not binary)
cmatrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2])
print(cmatrix)
total_samples = np.sum(cmatrix)

for i in range(3):
    true_positive = cmatrix[i, i]
    false_negative = np.sum(cmatrix[i, :]) - true_positive
    false_positive = np.sum(cmatrix[:, i]) - true_positive
    true_negative = total_samples - (true_positive + false_negative + false_positive)
    
    sensitivity = true_positive / (true_positive + false_negative) 
    specificity = true_negative / (true_negative + false_positive)
    
    print(f"Class {i}:")
    print(f">>sensitivity: {sensitivity}")
    print(f">>specificity: {specificity}")


Overall Accuracy: 0.944954128440367
[[23  0  0]
 [ 0 24  0]
 [ 3  3 56]]
Class 0:
>>sensitivity: 1.0
>>specificity: 0.9651162790697675
Class 1:
>>sensitivity: 1.0
>>specificity: 0.9647058823529412
Class 2:
>>sensitivity: 0.9032258064516129
>>specificity: 1.0


In [61]:
#implement KNN n=5
from sklearn.neighbors import KNeighborsClassifier
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train, y_train)
y_pred5 = knn5.predict(X_test)

In [62]:
#print confusion matrix
cmatrix5 = confusion_matrix(y_test, y_pred5, labels=[0, 1, 2])
print(cmatrix5)



[[23  0  0]
 [ 0 24  0]
 [ 3  3 56]]
